userSchema
Liettualainen/nodejs-homework-rest-api pull request #7
Opened 2023-08-02 18:02 UTC by Liettualainen

2023-08-04 07:36 UTC, ceREAL133 requested changes

2023-08-04 07:36 UTC, ceREAL133 commented on .env
> +DB_HOST=mongodb+srv://Mykhailo:vBADnnnXh7t9MA2u@cluster0.zkkdc5c.mongodb.net/db-contacts?retryWrites=true&w=majority
this is sensitive information. File .env must be hidden, add it to gitignore

2023-08-04 10:40 UTC, Liettualainen commented on .env
> +DB_HOST=mongodb+srv://Mykhailo:vBADnnnXh7t9MA2u@cluster0.zkkdc5c.mongodb.net/db-contacts?retryWrites=true&w=majority
have already corrected

2023-08-04 18:13 UTC, ceREAL133 requested changes

2023-08-04 18:13 UTC, ceREAL133 commented on .env
> +DB_HOST=mongodb+srv://Mykhailo:vBADnnnXh7t9MA2u@cluster0.zkkdc5c.mongodb.net/db-contacts?retryWrites=true&w=majority
why am i stiil able to see it here?

2023-08-04 18:29 UTC, Liettualainen commented on .env
> +DB_HOST=mongodb+srv://Mykhailo:vBADnnnXh7t9MA2u@cluster0.zkkdc5c.mongodb.net/db-contacts?retryWrites=true&w=majority
I supposed that after I decomment env in gitignor, file env would be deleted from git. Now I  deleted it, than  I created the same one but mentioned it in gitignor.

2023-08-05 14:23 UTC, ceREAL133 approved these changes

2023-08-07 13:03 UTC, merged